# Generated by Django 5.2.10 on 2026-01-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('english', models.TextField()),
                ('spanish', models.TextField()),
                ('difficulty', models.IntegerField(default=1)),
            ],
        ),
    ]
