# Generated by Django 5.2.10 on 2026-02-01 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='english',
            new_name='english_text',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='spanish',
            new_name='spanish_text',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title',
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
